// Generated by FlutterFire CLI (`flutterfire configure --project=advertisingscreen
// --platforms=web,macos,linux`) then relocated here to match this project's layout —
// FlutterFire CLI always writes to `lib/firebase_options.dart` by default; keep using
// `--out=lib/core/firebase/firebase_options.dart` next time to skip the manual move.
//
// Real values for the `advertisingscreen` Firebase project (Blaze plan). Do not
// commit changes to this file casually — regenerate via `flutterfire configure`
// instead of hand-editing, except for the `linux` case (see below).
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    // Uses Flutter's cross-platform TargetPlatform (not `dart:io`'s
    // `Platform`, which doesn't exist on web) so this file compiles on
    // every platform this app touches, web included.
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        // FlutterFire CLI doesn't support Linux directly (see
        // backend/README.md's "FlutterFire on Linux" risk note). Reusing
        // the macOS app's project-level values (apiKey/projectId/
        // storageBucket) here since they're valid for the same Firebase
        // project even without an official Linux SDK — FirebaseBootstrapper
        // handles the likely runtime failure gracefully either way.
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions has not been configured for this platform.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyCRuUWvwXpPhfOVgs7LCu9awuKEbzZZllE',
    appId: '1:1029613523965:web:ba748f389fb6a700cdff94',
    messagingSenderId: '1029613523965',
    projectId: 'advertisingscreen',
    authDomain: 'advertisingscreen.firebaseapp.com',
    storageBucket: 'advertisingscreen.firebasestorage.app',
    measurementId: 'G-38464BHGQY',
  );

  static const macos = FirebaseOptions(
    apiKey: 'AIzaSyDjFbAE1GiQp_NPIANO4WD4XF92-3UIJ2I',
    appId: '1:1029613523965:ios:1d88602f7ab842e1cdff94',
    messagingSenderId: '1029613523965',
    projectId: 'advertisingscreen',
    storageBucket: 'advertisingscreen.firebasestorage.app',
    iosBundleId: 'com.lumamarine.signage',
  );

  static const linux = FirebaseOptions(
    apiKey: 'AIzaSyDjFbAE1GiQp_NPIANO4WD4XF92-3UIJ2I',
    appId: '1:1029613523965:ios:1d88602f7ab842e1cdff94',
    messagingSenderId: '1029613523965',
    projectId: 'advertisingscreen',
    storageBucket: 'advertisingscreen.firebasestorage.app',
  );
}
